name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.6
        with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["label1"]'
      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"
